
package lt.viko.eif.rcepauskas.client.user;

import lt.viko.eif.rcepauskas.client.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UsersPort", targetNamespace = "http://localhost/web-service/user")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsersPort {


    /**
     * 
     * @param insertUserRequest
     * @return
     *     returns localhost.web_service.user.InsertUserResponse
     */
    @WebMethod
    @WebResult(name = "insertUserResponse", targetNamespace = "http://localhost/web-service/user", partName = "insertUserResponse")
    public InsertUserResponse insertUser(
        @WebParam(name = "insertUserRequest", targetNamespace = "http://localhost/web-service/user", partName = "insertUserRequest")
        InsertUserRequest insertUserRequest);

    /**
     * 
     * @param getUserRequest
     * @return
     *     returns localhost.web_service.user.GetUserResponse
     */
    @WebMethod
    @WebResult(name = "getUserResponse", targetNamespace = "http://localhost/web-service/user", partName = "getUserResponse")
    public GetUserResponse getUser(
        @WebParam(name = "getUserRequest", targetNamespace = "http://localhost/web-service/user", partName = "getUserRequest")
        GetUserRequest getUserRequest);

    /**
     * 
     * @param deleteUserRequest
     * @return
     *     returns localhost.web_service.user.DeleteUserResponse
     */
    @WebMethod
    @WebResult(name = "deleteUserResponse", targetNamespace = "http://localhost/web-service/user", partName = "deleteUserResponse")
    public DeleteUserResponse deleteUser(
        @WebParam(name = "deleteUserRequest", targetNamespace = "http://localhost/web-service/user", partName = "deleteUserRequest")
        DeleteUserRequest deleteUserRequest);

    /**
     * 
     * @param getUsersRequest
     * @return
     *     returns localhost.web_service.user.GetUsersResponse
     */
    @WebMethod
    @WebResult(name = "getUsersResponse", targetNamespace = "http://localhost/web-service/user", partName = "getUsersResponse")
    public GetUsersResponse getUsers(
        @WebParam(name = "getUsersRequest", targetNamespace = "http://localhost/web-service/user", partName = "getUsersRequest")
        GetUsersRequest getUsersRequest);

    /**
     * 
     * @param updateUserRequest
     * @return
     *     returns localhost.web_service.user.UpdateUserResponse
     */
    @WebMethod
    @WebResult(name = "updateUserResponse", targetNamespace = "http://localhost/web-service/user", partName = "updateUserResponse")
    public UpdateUserResponse updateUser(
        @WebParam(name = "updateUserRequest", targetNamespace = "http://localhost/web-service/user", partName = "updateUserRequest")
        UpdateUserRequest updateUserRequest);

}
