
package lt.viko.eif.rcepauskas.client.post;

import lt.viko.eif.rcepauskas.client.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PostsPort", targetNamespace = "http://localhost/web-service/post")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PostsPort {


    /**
     * 
     * @param deletePostRequest
     * @return
     *     returns localhost.web_service.post.DeletePostResponse
     */
    @WebMethod
    @WebResult(name = "deletePostResponse", targetNamespace = "http://localhost/web-service/post", partName = "deletePostResponse")
    public DeletePostResponse deletePost(
        @WebParam(name = "deletePostRequest", targetNamespace = "http://localhost/web-service/post", partName = "deletePostRequest")
        DeletePostRequest deletePostRequest);

    /**
     * 
     * @param insertPostRequest
     * @return
     *     returns localhost.web_service.post.InsertPostResponse
     */
    @WebMethod
    @WebResult(name = "insertPostResponse", targetNamespace = "http://localhost/web-service/post", partName = "insertPostResponse")
    public InsertPostResponse insertPost(
        @WebParam(name = "insertPostRequest", targetNamespace = "http://localhost/web-service/post", partName = "insertPostRequest")
        InsertPostRequest insertPostRequest);

    /**
     * 
     * @param getPostRequest
     * @return
     *     returns localhost.web_service.post.GetPostResponse
     */
    @WebMethod
    @WebResult(name = "getPostResponse", targetNamespace = "http://localhost/web-service/post", partName = "getPostResponse")
    public GetPostResponse getPost(
        @WebParam(name = "getPostRequest", targetNamespace = "http://localhost/web-service/post", partName = "getPostRequest")
        GetPostRequest getPostRequest);

    /**
     * 
     * @param updatePostRequest
     * @return
     *     returns localhost.web_service.post.UpdatePostResponse
     */
    @WebMethod
    @WebResult(name = "updatePostResponse", targetNamespace = "http://localhost/web-service/post", partName = "updatePostResponse")
    public UpdatePostResponse updatePost(
        @WebParam(name = "updatePostRequest", targetNamespace = "http://localhost/web-service/post", partName = "updatePostRequest")
        UpdatePostRequest updatePostRequest);

    /**
     * 
     * @param getPostsRequest
     * @return
     *     returns localhost.web_service.post.GetPostsResponse
     */
    @WebMethod
    @WebResult(name = "getPostsResponse", targetNamespace = "http://localhost/web-service/post", partName = "getPostsResponse")
    public GetPostsResponse getPosts(
        @WebParam(name = "getPostsRequest", targetNamespace = "http://localhost/web-service/post", partName = "getPostsRequest")
        GetPostsRequest getPostsRequest);

}
