
package lt.viko.eif.rcepauskas.client.post;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PostsPortService", targetNamespace = "http://localhost/web-service/post", wsdlLocation = "http://localhost:8080/ws/posts.wsdl")
public class PostsPortService
    extends Service
{

    private final static URL POSTSPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException POSTSPORTSERVICE_EXCEPTION;
    private final static QName POSTSPORTSERVICE_QNAME = new QName("http://localhost/web-service/post", "PostsPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/posts.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POSTSPORTSERVICE_WSDL_LOCATION = url;
        POSTSPORTSERVICE_EXCEPTION = e;
    }

    public PostsPortService() {
        super(__getWsdlLocation(), POSTSPORTSERVICE_QNAME);
    }

    public PostsPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), POSTSPORTSERVICE_QNAME, features);
    }

    public PostsPortService(URL wsdlLocation) {
        super(wsdlLocation, POSTSPORTSERVICE_QNAME);
    }

    public PostsPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POSTSPORTSERVICE_QNAME, features);
    }

    public PostsPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PostsPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PostsPort
     */
    @WebEndpoint(name = "PostsPortSoap11")
    public PostsPort getPostsPortSoap11() {
        return super.getPort(new QName("http://localhost/web-service/post", "PostsPortSoap11"), PostsPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostsPort
     */
    @WebEndpoint(name = "PostsPortSoap11")
    public PostsPort getPostsPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/web-service/post", "PostsPortSoap11"), PostsPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POSTSPORTSERVICE_EXCEPTION!= null) {
            throw POSTSPORTSERVICE_EXCEPTION;
        }
        return POSTSPORTSERVICE_WSDL_LOCATION;
    }

}
